trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  # Autentica para Azure Artifacts (se usar feeds privados)
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  # Restaura no agente
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    displayName: 'dotnet restore'

  # Publica no agente (output em Build.ArtifactStagingDirectory/publish)
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/publish --no-restore'
    displayName: 'dotnet publish'

  # Build e push do container usando a pasta publish como contexto
  - task: Docker@2
    inputs:
      containerRegistry: 'dotnetmssqlrm555217'    # seu service connection
      repository: 'dotnetsql'
      command: 'buildAndPush'
      Dockerfile: 'docker/Dockerfile.runtime'    # caminho explícito do Dockerfile runtime
      buildContext: '$(Build.ArtifactStagingDirectory)/publish'
      tags: |
        $(Build.BuildId)
        latest
    displayName: 'Docker build and push (from published files)'