-- Tabela USUARIO
CREATE TABLE USUARIO (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Senha NVARCHAR(255) NOT NULL,
    Tipo INT NOT NULL
);

-- Tabela MOTO
CREATE TABLE MOTO (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Modelo NVARCHAR(50) NOT NULL,
    Placa NVARCHAR(10) NOT NULL UNIQUE,
    Chassi NVARCHAR(50) NOT NULL UNIQUE,
    ProblemaIdentificado NVARCHAR(255) NULL
);